### PR TITLE
Improve UX

### LINKED ISSUE #3: Static template QA
- [x] Add meta description: "Shop for broadband cable services in your area. See plans, prices, and schedule your service."
- [x] Add blue overlay, or underlay to video background, per design
- [x] In footer, adjust "Questions?" to be left aligned with contact form
- [x] Change the dropdown selection hover color from that bright blue to the darker blue
- [x] Change the selected checkbox to be the darker blue vs the brighter blue
- [x] Change button hover styling for all yellow buttons to just have the font color change to the default dark grey body font color - & no animation on hover please
- [x] Align footer “Powered by…” with left side of contact form/page template
- [x] Add slight text shadow to heading text in logo section
- [x] Adjust left right padding in between mobile and desktop (keep the padding nice and chunky) Get with kyle to go over.
- [x] On desktop, inputs to be 70px tall and GO button to be 70px square
- [x] For mobile, replace video with the static image
- [x] For mobile, when placeholder font becomes smaller on active, make that font even smaller than it is now

The candy:
- [x] add a simple/elegant page load, maybe a simple fade-in
- [x] add “section wipe” scroll on the top video section
- [x] animate "Zoom in” effect with logos when you scroll to them

### PR DESCRIPTION
**Pull request by NathanBurkett**
Closes #3 
#### How should the reviewer test this?
- Navigate to http://dev.bythepixel.com/kyrio/ and ensure site follows QA from #3

### CODE REVIEW

**Comment by KyleKrukar** [comment]
@NathanBurkett this should be the last of it. Thanks.
- [x] Need 2x for main GO2 logo
- [x] For the logos section, animate just the single container that is wrapping around the logos. Perhaps animating a padding change? see gif
- [x] header and footer, between 850-1200 adjust left and right spacing per mocks
- [x] add preloader from www.kyrio.com, centered vertically and horizontally
- [x] remove `text-shadow` on page header heading text

logozoom

1200hero

1200foot

**Comment by NathanBurkett** [comment]
> For the logos section, animate just the single container that is wrapping around the logos. Perhaps animating a padding change? see gif

👍  🎉  Big fan of this one. It'll cut down on page ux weight a ton

**Comment by NathanBurkett** [comment]
@KyleKrukar Just so we're clear. The buttons changing text color effect is good?

**Comment by KyleKrukar** [comment]
yup! @NathanBurkett

**Comment by NathanBurkett** [comment]
:+1:

**Pull request merged**
