### PR TITLE
Pixel and kyrio content combined

### PR DESCRIPTION
**Pull request by ColoradoOrion**
This pulls in some of the changes I've made while working on the header. It also disables the checkbox logic as I'm using the method we us elsewhere (at least for now). This avoids the impression we're clicking the checkbox for the user against their wishes.

I've done some re-org. I've done the best with templates given my understanding of nunjucks. Feel free to make suggestions. Affiliate index.html isn't quite there. I'll double back once I'm closer to implementing some of this logic. As it is, we use our own wired-in versions of the views and just use the templates for sanity checks.

I believe there is a merge conflict with either app.css or app.js. Since we rebuild, this shouldn't be a problem.

### CODE REVIEW

**Comment by NathanBurkett** [comment]
@ColoradoOrion To be clear - we're not pulling in these changes:
- Changes made while working on the header
- Disabled checkbox logic
- Re-organization of nunjucks templating

Instead we're merging in the below changes into the above listed changes:
- Change sass output in build process
- Fix checkbox alignment in smaller viewports

---

I'm going to go ahead and fix the conflict, push the change, and approve the PR. I'll approve with a thumbs up (:+1:) and re-assign the PR back to you when I'm finished reviewing. Thanks!

**Review by NathanBurkett — APPROVED** [review]
:+1:

**Comment by ColoradoOrion** [comment]
Thanks for dealing with the merge conflicts, Nathan. So I'm clear, what's our definitive branch now and when should we get ourselves back to master? We have a deploy tomorrow to production, which is when we typically merge back into master.

**Comment by ColoradoOrion** [comment]
I think I answered my first question by doing the merge i.e. HeaderIconStyling is now the operative branch. At what point in your flow do you merge back into master?

**Comment by NathanBurkett** [comment]
@ColoradoOrion We don't operate with `dev` branches at BTP so our feature/hotfix branches merge directly into `master`. We also don't maintain a `staging` branch parallel to `master` - we create temp branches or push feature branches directly to our staging environments when we run QA, collaborate on testing, smoke test multiple features together, etc.

**So to answer your question** - when a feature has been properly vetted by our standards, we'll merge it back into master and create a new release. We don't push releases on hard time constraints (other than deadlines) like nightly, weekly, bi-weekly - we do it based upon merit and completion.

**Pull request merged**
